---
- hosts: localhost
  become: yes

  tasks:
  
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - zsh
        - mc
        - htop
        - feh
        - lutris
        - terminator
        - mc
        - ranger
        - vlc
        - jq
        - cmus
        - npm
        - wine
        - steam
        - docker
        - neofetch
        - mpd
        - mpv
        - fonts-powerline
    
    - name: Check if vim_runtime folder exists for awesome vimrc
      stat:
        path: ~/.vim_runtime
      register: awesome_vimrc
      
    # Download and install awesome vimrc
    
    - name: download awesome vimrc
      git:
        repo: https://github.com/amix/vimrc.git
        dest: ~/.vim_runtime
        depth: 1
      when: not awesome_vimrc.stat.exists
      
    - name: make ultimate vimrc executable
      file:
        path: ~/.vim_runtime/install_awesome_vimrc.sh
        mode: '0755'
    - name: install awesome vimrc
      command: ~/.vim_runtime/install_awesome_vimrc.sh
      
    # Download and install oh-my-zsh and install plugins
    - name: install curl oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
      args:
        chdir: ~/
      ignore_errors: yes

    - name: install zsh plugins
      git:
        repo: "https://github.com/{{ item.src }}"
        dest: "~/.oh-my-zsh/custom/plugins/{{ item.dest }}"
        depth: 1
      loop:
        - { src: 'zsh-users/zsh-syntax-highlighting.git', dest: 'zsh-syntax-highlighting' }
        - { src: 'zsh-users/zsh-completions', dest: 'zsh-completions' }
        - { src: 'zsh-users/zsh-history-substring-search', dest: 'zsh-history-substring-search' }
        - { src: 'supercrabtree/k', dest: 'k' }
        - { src: 'wfxr/forgit.git', dest: 'forgit' }
      ignore_errors: yes        
   
        # Download and install fzf (required for forgit zsh plugin)
   
    - name: download fzf
      git:
        repo: "https://github.com/junegunn/fzf.git"
        dest: "~/.fzf"
        depth: 1
    - name: install fzxf
      shell: ~/.fzf/install
   
        # Create config folders

    - name: Creates mc config directory
      file:
        path: ~/.config/mc
        state: directory

    - name: Creates terminator config directory
      file:
        path: ~/.config/terminator
        state: directory

    - name: Creates i3 config directory
      file:
        path: ~/.config/i3
        state: directory
   
    - name: create variety scripts folder
      file:
        path: ~/.config/variety/scripts
        state: directory

        # Copy configs and dotfiles

    - name: vimrc 
      template:
       src: ~/git/tools_of_the_trade/dotfiles/vimrc
       dest: ~/.vimrc

    - name: mc-settings 
      template:
       src: ~/git/tools_of_the_trade/dotfiles/mc-ini
       dest: ~/.config/mc/ini


    - name: i3-config 
      template:
       src: ~/git/tools_of_the_trade/dotfiles/i3/config 
       dest: ~/.config/i3/config
 
    - name: terminator config 
      template:
       src: ~/git/tools_of_the_trade/dotfiles/terminator
       dest: ~/.config/terminator/config

    - name: picom-config
      template:
       src: ~/git/tools_of_the_trade/dotfiles/i3/picom
       dest: ~/.config/picom.conf
   
    - name: zshrc-config
      template:
       src: ~/git/tools_of_the_trade/dotfiles/zshrc
       dest: ~/.zshrc
       
    # Install peerflix
    - name: Install peerflix
      shell: npm install -g peerflix

    # Adding ZSH to default
   
    - name: change default shell
      shell: chsh -s /bin/zsh 

