---

- hosts: localhost
    become: True

tasks:
 
     - include_role:
         name: linux_package
       vars:
         packages:
           - git
           - python-pip
           - gcc
           - libffi-devel
           - python-devel
           - openssl-devel
           - vim
           - wget
           - python-virtualenv
           - mc
           - tmux
           - htop
           - ncurses-devel
           - git-core
           - lynx
   
    - name: Apply Midnight Commander settings 
      template:
        src: /custom_config/ini.j2 
        dest: ~/.config/mc/ini

    - name: Install Vim from source:
        shell: cd .. && git clone https://github.com/vim/vim.git && ./configure --prefix=/usr --with-features=huge --enable-multibyte --with-python-config-dir=/usr/lib/python2.7/config --enable-pythoninterp=yes && cd vim && make install

    - name: Install VimAwesome
        shell: cd .. && git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime && sh ~/.vim_runtime/install_awesome_vimrc.sh



