---

- hosts: localhost
    become: True

tasks:
 
     - name: create /deployment folder
       file:
         path: /deployment
         owner: remus
         group: remus
         state: directory
         mode: 0777

     - include_role:
         name: linux_package
       vars:
         packages:
           - git
           - python-pip
           - gcc
           - libffi-devel
           - python-devel
           - openssl-devel
           - vim
           - wget
           - python-virtualenv
           - mc
           - tmux
           - htop
           - ncurses-devel
           - git-core
           - lynx
   
    - name: Apply Midnight Commander settings 
      src: /custom_config/ini 
      dest: ~/.config/mc/ini
