---
- hosts: localhost
  become_user: remus
  become: yes

  tasks:
    - name: Setup Solus script
      script: ~/git/tools_of_the_trade/setup-solus.sh
   
    # quick check to make sure vimrc doesnt exist already, if it does then skip it 
    - name: Check if vim_runtime folder exists for awesome vimrc
      stat:
        path: ~/.vim_runtime
      register: awesome_vimrc
    # Download and install awesome vimrc
    - name: download awesome vimrc
      git:
        repo: https://github.com/amix/vimrc.git
        dest: ~/.vim_runtime
        depth: 1
      when: not awesome_vimrc.stat.exists
    - name: make ultimate vimrc executable
      file:
        path: ~/.vim_runtime/install_awesome_vimrc.sh
        mode: '0755'
    - name: install awesome vimrc
      command: ~/.vim_runtime/install_awesome_vimrc.sh
      
    # Download and install oh-my-zsh and install plugins
    - name: install curl oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
      args:
        chdir: ~/
      ignore_errors: yes

    - name: install zsh plugins
      git:
        repo: "https://github.com/{{ item.src }}"
        dest: "~/.oh-my-zsh/custom/plugins/{{ item.dest }}"
        depth: 1
      loop:
        - { src: 'zsh-users/zsh-syntax-highlighting.git', dest: 'zsh-syntax-highlighting' }
        - { src: 'zsh-users/zsh-completions', dest: 'zsh-completions' }
        - { src: 'zsh-users/zsh-history-substring-search', dest: 'zsh-history-substring-search' }
        - { src: 'supercrabtree/k', dest: 'k' }
        - { src: 'wfxr/forgit.git', dest: 'forgit' }
      ignore_errors: yes        
    # Download and install fzf (required for forgit zsh plugin)
    - name: download fzf
      git:
        repo: "https://github.com/junegunn/fzf.git"
        dest: "~/.fzf"
        depth: 1
    - name: install fzxf
      shell: ~/.fzf/install

    - name: Creates mc config directory
      file:
        path: ~/.config/mc
        state: directory
    - name: Creates i3 config directory
      file:
        path: ~/.config/i3
        state: directory
    - name: create variety scripts folder
      file:
        path: ~/.config/variety/scripts
        state: directory
    - name: mc-settings 
      template:
       src: ~/git/tools_of_the_trade/dotfiles/ini.j2 
       dest: ~/.config/mc/ini
    # Copy AppImages
    - name: Create an appimages folder
      file:
        path: ~/appimages
        state: directory
        mode: '0755' 
    - name: Copy FreeTube
      copy:
        src: ~/git/tools_of_the_trade/appimages/freetube.AppImage
        dest: ~/appimages/freetube.AppImage
        mode: u+rwx,g-wx,o-rx
    - name: Copy OpenRA 
      copy:
        src: ~/git/tools_of_the_trade/appimages/openra.AppImage
        dest: ~/appimages/openra.AppImage
        mode: u+rwx,g-wx,o-rx
    - name: Copy pCloud
      copy:
        src: ~/git/tools_of_the_trade/appimages/pcloud.AppImage
        dest: ~/appimages/pcloud.AppImages
        mode: u+rwx,g-wx,o-rx     
    # Copy configs and dotfiles
    - name: vimrc 
      template:
       src: ~/git/tools_of_the_trade/dotfiles/vimrc.j2 
       dest: ~/.vimrc

    - name: i3-config 
      template:
       src: ~/git/tools_of_the_trade/dotfiles/i3/config.j2 
       dest: ~/.config/i3/config
  
    - name: compton-config
      template:
       src: ~/git/tools_of_the_trade/dotfiles/i3/compton.j2 
       dest: ~/.config/.compton.conf
    - name: zshrc-config
      template:
       src: ~/git/tools_of_the_trade/dotfiles/zshrc.j2
       dest: ~/.zshrc
    - name: variety
      template:
       src: ~/git/tools_of_the_trade/dotfiles/variety.j2
       dest: ~/.config/variety/scripts/set_wallpaper

    #Installing Snaps
    #    - name: Install VS Code
    #  snap:
    #    name: code
    #    classic: yes
    #  become_user: root
    #- name: Install snaps
    #  snap:
    #    name:
    #      - cataclysm
    #      - cnctsun
    #  become_user: root

    # Adding ZSH to default
    - name: change default shell
      shell: sudo chsh -s /bin/zsh $(whoami)
